### ISSUE TITLE
empty result file

### ISSUE THREAD

**Issue by danessel** [asdcid/single-copy-direction-chloroplast#3]
Hi, nice tool, in the past we developed a CP assembly tool based on illumina reads but the orientations had to be verified using additional PCRs . I've used you tool and i have ONT reads covering the brakepoints but the end result file is empty. All other files are there and the test run was also succesfull. Any idea ? Coverage too high ...
![image](https://user-images.githubusercontent.com/7812782/117271238-44d48480-ae5a-11eb-8718-d1aab42188c2.png)

**Comment by asdcid** [comment]
Hi Danessel,

Thanks for your interest in my tool.

I have no clue what caused this now.

Could you send me the chloroplast genome (`.fasta`) you used as the input, and the first 2,000 lines of the minimap outputFile (`.paf`)? Then I can have a look. My email is wei.wang@anu.edu.au

Thanks,
www

**Comment by danessel** [comment]
Hi  www,

Thanks for the quick response
Attached the requested files

Danny

**Comment by danessel** [comment]
Hi,

I used a different assembler, shasta instead of fly and then the outcome is:
Structure_name  number_of_supported_reads
LSC_IR_SSCrc_IRrc

So exactly what i figured out by mapping myself.

Danny

**Comment by danessel** [comment]
But no fasta output

From: Esselink, Danny
Sent: maandag 10 mei 2021 13:28
To: asdcid/Cp-hap ***@***.***>
Subject: RE: [asdcid/Cp-hap] empty result file (#3)

Hi,

I used a different assembler, shasta instead of fly and then the outcome is:
Structure_name  number_of_supported_reads
LSC_IR_SSCrc_IRrc

So exactly what i figured out by mapping myself.

Danny

**Comment by asdcid** [comment]
Sorry, I can't find your attached files. Have you sent them to my email?

**Comment by danessel** [comment]
From: Esselink, Danny ***@***.***>
Sent: maandag 10 mei 2021 8:04
To: asdcid/Cp-hap ***@***.***>
Subject: RE: [asdcid/Cp-hap] empty result file (#3)

Hi  www,

Thanks for the quick response
Attached the requested files

Danny

**Comment by asdcid** [comment]
Sorry, are you sure you have attached it? I can't find it. If you attached it with Github, Github only supports a few file types, not all. Could you send it to my email? My email is wei.wang@anu.edu.au
