### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by yanzhongsino** [asdcid/single-copy-direction-chloroplast#4]
Hi, nice tool. I found a syntax error when I used in my data.

"File "/soft/Cp-hap/scripts/parse.py", line 86
    o.write('Haven't detected reads which are long enough to support the structures')
                   ^
SyntaxError: invalid syntax"

It can work well when I changed all "haven't" in file parse.py to "have not".  So I think this is an error caused by the syntax of single quotes.

**Comment by asdcid** [comment]
Sorry for this error. This command worked in some old python versions. I have changed it now. Thanks for telling!
